import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Createtodo from '@/components/createToDo/createtodo';
import Todos from '@/components/todos';
import ContextComponent from './contextTodos';

import Searchbox from '@/components/search/search';
import Todo from '@/components/todo/todo';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>To Do App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <ContextComponent>
          <Createtodo />
          <Searchbox />
          <Todos />
        </ContextComponent>
      </div>
    </>
  );
}
